# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mianWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(870, 661)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../conf/ICON.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab1)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.spinBox_year = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_year.setMinimum(2019)
        self.spinBox_year.setMaximum(2020)
        self.spinBox_year.setObjectName("spinBox_year")
        self.horizontalLayout_3.addWidget(self.spinBox_year)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.spinBox_month = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_month.setMinimum(1)
        self.spinBox_month.setMaximum(12)
        self.spinBox_month.setObjectName("spinBox_month")
        self.horizontalLayout_3.addWidget(self.spinBox_month)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(5, 1)
        self.horizontalLayout_3.setStretch(6, 2)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(self.tab1)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btn_table_house_insurance = QtWidgets.QPushButton(self.groupBox)
        self.btn_table_house_insurance.setObjectName("btn_table_house_insurance")
        self.gridLayout.addWidget(self.btn_table_house_insurance, 2, 3, 1, 1)
        self.btn_table_endowment_insurance_roster = QtWidgets.QPushButton(self.groupBox)
        self.btn_table_endowment_insurance_roster.setObjectName("btn_table_endowment_insurance_roster")
        self.gridLayout.addWidget(self.btn_table_endowment_insurance_roster, 2, 0, 1, 1)
        self.btn_table_people_info = QtWidgets.QPushButton(self.groupBox)
        self.btn_table_people_info.setObjectName("btn_table_people_info")
        self.gridLayout.addWidget(self.btn_table_people_info, 0, 3, 1, 1)
        self.btn_table_tax_extra = QtWidgets.QPushButton(self.groupBox)
        self.btn_table_tax_extra.setObjectName("btn_table_tax_extra")
        self.gridLayout.addWidget(self.btn_table_tax_extra, 4, 0, 1, 1)
        self.btn_table_endowment_insurance_detail = QtWidgets.QPushButton(self.groupBox)
        self.btn_table_endowment_insurance_detail.setObjectName("btn_table_endowment_insurance_detail")
        self.gridLayout.addWidget(self.btn_table_endowment_insurance_detail, 2, 1, 1, 1)
        self.btn_table_position_change = QtWidgets.QPushButton(self.groupBox)
        self.btn_table_position_change.setObjectName("btn_table_position_change")
        self.gridLayout.addWidget(self.btn_table_position_change, 0, 1, 1, 1)
        self.btn_table_sap_workday = QtWidgets.QPushButton(self.groupBox)
        self.btn_table_sap_workday.setObjectName("btn_table_sap_workday")
        self.gridLayout.addWidget(self.btn_table_sap_workday, 0, 2, 1, 1)
        self.btn_table_unemployment_insurance_detail = QtWidgets.QPushButton(self.groupBox)
        self.btn_table_unemployment_insurance_detail.setObjectName("btn_table_unemployment_insurance_detail")
        self.gridLayout.addWidget(self.btn_table_unemployment_insurance_detail, 2, 2, 1, 1)
        self.btn_table_standard = QtWidgets.QPushButton(self.groupBox)
        self.btn_table_standard.setObjectName("btn_table_standard")
        self.gridLayout.addWidget(self.btn_table_standard, 0, 0, 1, 1)
        self.btn_table_insurance_extra_payment = QtWidgets.QPushButton(self.groupBox)
        self.btn_table_insurance_extra_payment.setObjectName("btn_table_insurance_extra_payment")
        self.gridLayout.addWidget(self.btn_table_insurance_extra_payment, 3, 3, 1, 1)
        self.btn_table_extra_workincome = QtWidgets.QPushButton(self.groupBox)
        self.btn_table_extra_workincome.setObjectName("btn_table_extra_workincome")
        self.gridLayout.addWidget(self.btn_table_extra_workincome, 4, 3, 1, 1)
        self.btn_table_last_month_tax_detail = QtWidgets.QPushButton(self.groupBox)
        self.btn_table_last_month_tax_detail.setObjectName("btn_table_last_month_tax_detail")
        self.gridLayout.addWidget(self.btn_table_last_month_tax_detail, 4, 2, 1, 1)
        self.btn_table_medical_insurance_detail = QtWidgets.QPushButton(self.groupBox)
        self.btn_table_medical_insurance_detail.setObjectName("btn_table_medical_insurance_detail")
        self.gridLayout.addWidget(self.btn_table_medical_insurance_detail, 3, 1, 1, 1)
        self.btn_table_civil_servants_insurance_detail = QtWidgets.QPushButton(self.groupBox)
        self.btn_table_civil_servants_insurance_detail.setObjectName("btn_table_civil_servants_insurance_detail")
        self.gridLayout.addWidget(self.btn_table_civil_servants_insurance_detail, 3, 2, 1, 1)
        self.btn_table_tax_remove = QtWidgets.QPushButton(self.groupBox)
        self.btn_table_tax_remove.setObjectName("btn_table_tax_remove")
        self.gridLayout.addWidget(self.btn_table_tax_remove, 4, 1, 1, 1)
        self.btn_table_medical_insurance_roster = QtWidgets.QPushButton(self.groupBox)
        self.btn_table_medical_insurance_roster.setObjectName("btn_table_medical_insurance_roster")
        self.gridLayout.addWidget(self.btn_table_medical_insurance_roster, 3, 0, 1, 1)
        self.btn_last_month_wage_detail = QtWidgets.QPushButton(self.groupBox)
        self.btn_last_month_wage_detail.setObjectName("btn_last_month_wage_detail")
        self.gridLayout.addWidget(self.btn_last_month_wage_detail, 5, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab1)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_finace_new_info = QtWidgets.QPushButton(self.groupBox_5)
        self.btn_finace_new_info.setObjectName("btn_finace_new_info")
        self.horizontalLayout_4.addWidget(self.btn_finace_new_info)
        self.btn_finace_tax_calc_template = QtWidgets.QPushButton(self.groupBox_5)
        self.btn_finace_tax_calc_template.setObjectName("btn_finace_tax_calc_template")
        self.horizontalLayout_4.addWidget(self.btn_finace_tax_calc_template)
        self.horizontalLayout_5.addWidget(self.groupBox_5)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_workincome_calc = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_workincome_calc.setObjectName("btn_workincome_calc")
        self.gridLayout_2.addWidget(self.btn_workincome_calc, 0, 0, 1, 1)
        self.btn_workincome_summary = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_workincome_summary.setObjectName("btn_workincome_summary")
        self.gridLayout_2.addWidget(self.btn_workincome_summary, 0, 1, 1, 1)
        self.btn_wage_split = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_wage_split.setObjectName("btn_wage_split")
        self.gridLayout_2.addWidget(self.btn_wage_split, 0, 3, 1, 1)
        self.btn_workincome_detail = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_workincome_detail.setObjectName("btn_workincome_detail")
        self.gridLayout_2.addWidget(self.btn_workincome_detail, 0, 2, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        self.horizontalLayout_5.addWidget(self.groupBox_4)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.verticalLayout_2.setStretch(0, 2)
        self.verticalLayout_2.setStretch(1, 8)
        self.verticalLayout_2.setStretch(2, 4)
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab2)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.label_4 = QtWidgets.QLabel(self.groupBox_7)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.spinBox_bouns_year = QtWidgets.QSpinBox(self.groupBox_7)
        self.spinBox_bouns_year.setMinimum(2019)
        self.spinBox_bouns_year.setMaximum(2020)
        self.spinBox_bouns_year.setObjectName("spinBox_bouns_year")
        self.horizontalLayout_7.addWidget(self.spinBox_bouns_year)
        self.label_5 = QtWidgets.QLabel(self.groupBox_7)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.spinBox_bouns_month = QtWidgets.QSpinBox(self.groupBox_7)
        self.spinBox_bouns_month.setMinimum(1)
        self.spinBox_bouns_month.setMaximum(12)
        self.spinBox_bouns_month.setObjectName("spinBox_bouns_month")
        self.horizontalLayout_7.addWidget(self.spinBox_bouns_month)
        self.label_6 = QtWidgets.QLabel(self.groupBox_7)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.horizontalLayout_7.setStretch(0, 2)
        self.horizontalLayout_7.setStretch(1, 1)
        self.horizontalLayout_7.setStretch(5, 1)
        self.horizontalLayout_7.setStretch(6, 2)
        self.verticalLayout_3.addWidget(self.groupBox_7)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab2)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.btn_sum_excel_to_sql = QtWidgets.QPushButton(self.groupBox_6)
        self.btn_sum_excel_to_sql.setObjectName("btn_sum_excel_to_sql")
        self.horizontalLayout_11.addWidget(self.btn_sum_excel_to_sql)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem5)
        self.btn_bouns_extra = QtWidgets.QPushButton(self.groupBox_6)
        self.btn_bouns_extra.setObjectName("btn_bouns_extra")
        self.horizontalLayout_11.addWidget(self.btn_bouns_extra)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem6)
        self.verticalLayout_3.addWidget(self.groupBox_6)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab2)
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.btn_finace_tax_calc_template_2 = QtWidgets.QPushButton(self.groupBox_9)
        self.btn_finace_tax_calc_template_2.setObjectName("btn_finace_tax_calc_template_2")
        self.horizontalLayout_9.addWidget(self.btn_finace_tax_calc_template_2)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.horizontalLayout_8.addWidget(self.groupBox_9)
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_10.setObjectName("groupBox_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBox_10)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_workincome_summary_2 = QtWidgets.QPushButton(self.groupBox_10)
        self.btn_workincome_summary_2.setObjectName("btn_workincome_summary_2")
        self.gridLayout_3.addWidget(self.btn_workincome_summary_2, 0, 1, 1, 1)
        self.btn_bouns_detail = QtWidgets.QPushButton(self.groupBox_10)
        self.btn_bouns_detail.setObjectName("btn_bouns_detail")
        self.gridLayout_3.addWidget(self.btn_bouns_detail, 0, 2, 1, 1)
        self.btn_bouns_calc = QtWidgets.QPushButton(self.groupBox_10)
        self.btn_bouns_calc.setObjectName("btn_bouns_calc")
        self.gridLayout_3.addWidget(self.btn_bouns_calc, 0, 0, 1, 1)
        self.btn_wage_split_2 = QtWidgets.QPushButton(self.groupBox_10)
        self.btn_wage_split_2.setObjectName("btn_wage_split_2")
        self.gridLayout_3.addWidget(self.btn_wage_split_2, 0, 3, 1, 1)
        self.horizontalLayout_10.addLayout(self.gridLayout_3)
        self.horizontalLayout_8.addWidget(self.groupBox_10)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 2)
        self.verticalLayout_3.addWidget(self.groupBox_8)
        self.verticalLayout_3.setStretch(0, 3)
        self.verticalLayout_3.setStretch(1, 5)
        self.verticalLayout_3.setStretch(2, 5)
        self.tabWidget.addTab(self.tab2, "")
        self.tab3 = QtWidgets.QWidget()
        self.tab3.setObjectName("tab3")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab3)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 160, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab3)
        self.groupBox_11.setGeometry(QtCore.QRect(0, 30, 828, 78))
        self.groupBox_11.setObjectName("groupBox_11")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_11)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.label_7 = QtWidgets.QLabel(self.groupBox_11)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.spinBox_year_2 = QtWidgets.QSpinBox(self.groupBox_11)
        self.spinBox_year_2.setMinimum(2019)
        self.spinBox_year_2.setMaximum(2020)
        self.spinBox_year_2.setObjectName("spinBox_year_2")
        self.horizontalLayout_6.addWidget(self.spinBox_year_2)
        self.label_8 = QtWidgets.QLabel(self.groupBox_11)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.spinBox_month_2 = QtWidgets.QSpinBox(self.groupBox_11)
        self.spinBox_month_2.setMinimum(1)
        self.spinBox_month_2.setMaximum(12)
        self.spinBox_month_2.setObjectName("spinBox_month_2")
        self.horizontalLayout_6.addWidget(self.spinBox_month_2)
        self.label_9 = QtWidgets.QLabel(self.groupBox_11)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.horizontalLayout_6.setStretch(0, 2)
        self.horizontalLayout_6.setStretch(1, 1)
        self.horizontalLayout_6.setStretch(5, 1)
        self.horizontalLayout_6.setStretch(6, 2)
        self.tabWidget.addTab(self.tab3, "")
        self.tab4 = QtWidgets.QWidget()
        self.tab4.setObjectName("tab4")
        self.tabWidget.addTab(self.tab4, "")
        self.verticalLayout.addWidget(self.tabWidget)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 870, 23))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "河钢乐亭薪酬管理系统"))
        self.groupBox_3.setTitle(_translate("mainWindow", "第一步：日期确定"))
        self.label.setText(_translate("mainWindow", "请输入工资核算日期："))
        self.label_2.setText(_translate("mainWindow", "年"))
        self.label_3.setText(_translate("mainWindow", "月"))
        self.groupBox.setTitle(_translate("mainWindow", "第二步：数据导入"))
        self.btn_table_house_insurance.setText(_translate("mainWindow", "公积金缴费明细"))
        self.btn_table_endowment_insurance_roster.setText(_translate("mainWindow", "养老保险花名册"))
        self.btn_table_people_info.setText(_translate("mainWindow", "人员信息表"))
        self.btn_table_tax_extra.setText(_translate("mainWindow", "财务附加计税明细"))
        self.btn_table_endowment_insurance_detail.setText(_translate("mainWindow", "养老保险缴费明细"))
        self.btn_table_position_change.setText(_translate("mainWindow", "岗位变更表"))
        self.btn_table_sap_workday.setText(_translate("mainWindow", "sap考勤表"))
        self.btn_table_unemployment_insurance_detail.setText(_translate("mainWindow", "失业保险缴费明细"))
        self.btn_table_standard.setText(_translate("mainWindow", "工资标准表"))
        self.btn_table_insurance_extra_payment.setText(_translate("mainWindow", "保险补缴明细"))
        self.btn_table_extra_workincome.setText(_translate("mainWindow", "工资补发补扣"))
        self.btn_table_last_month_tax_detail.setText(_translate("mainWindow", "上月缴税明细"))
        self.btn_table_medical_insurance_detail.setText(_translate("mainWindow", "医疗保险缴费明细"))
        self.btn_table_civil_servants_insurance_detail.setText(_translate("mainWindow", "公务员医疗缴费明细"))
        self.btn_table_tax_remove.setText(_translate("mainWindow", "个人附加扣除"))
        self.btn_table_medical_insurance_roster.setText(_translate("mainWindow", "医疗保险缴费花名册"))
        self.btn_last_month_wage_detail.setText(_translate("mainWindow", "上月工资明细表"))
        self.groupBox_2.setTitle(_translate("mainWindow", "第三步：工资生成"))
        self.groupBox_5.setTitle(_translate("mainWindow", "财务"))
        self.btn_finace_new_info.setText(_translate("mainWindow", "新增人员信息"))
        self.btn_finace_tax_calc_template.setText(_translate("mainWindow", "正常薪金所得（算税模板）"))
        self.groupBox_4.setTitle(_translate("mainWindow", "人力"))
        self.btn_workincome_calc.setText(_translate("mainWindow", "工资计算"))
        self.btn_workincome_summary.setText(_translate("mainWindow", "工资汇总表"))
        self.btn_wage_split.setText(_translate("mainWindow", "工资拆分表"))
        self.btn_workincome_detail.setText(_translate("mainWindow", "工资明细表"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("mainWindow", "工资核算"))
        self.groupBox_7.setTitle(_translate("mainWindow", "第一步：日期确定"))
        self.label_4.setText(_translate("mainWindow", "请输入奖金核算日期："))
        self.label_5.setText(_translate("mainWindow", "年"))
        self.label_6.setText(_translate("mainWindow", "月"))
        self.groupBox_6.setTitle(_translate("mainWindow", "第二部：数据导入"))
        self.btn_sum_excel_to_sql.setText(_translate("mainWindow", "本月各部门绩效汇总"))
        self.btn_bouns_extra.setText(_translate("mainWindow", "奖金补发补扣"))
        self.groupBox_8.setTitle(_translate("mainWindow", "第三步：奖金生成"))
        self.groupBox_9.setTitle(_translate("mainWindow", "财务"))
        self.btn_finace_tax_calc_template_2.setText(_translate("mainWindow", "正常薪金所得（算税模板）"))
        self.groupBox_10.setTitle(_translate("mainWindow", "人力"))
        self.btn_workincome_summary_2.setText(_translate("mainWindow", "奖金汇总表"))
        self.btn_bouns_detail.setText(_translate("mainWindow", "奖金明细表"))
        self.btn_bouns_calc.setText(_translate("mainWindow", "奖金计算"))
        self.btn_wage_split_2.setText(_translate("mainWindow", "奖金拆分表"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("mainWindow", "奖金核算"))
        self.pushButton_2.setText(_translate("mainWindow", "下月预算表"))
        self.groupBox_11.setTitle(_translate("mainWindow", "第一步：日期确定"))
        self.label_7.setText(_translate("mainWindow", "请输入工资核算日期："))
        self.label_8.setText(_translate("mainWindow", "年"))
        self.label_9.setText(_translate("mainWindow", "月"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3), _translate("mainWindow", "报表生成"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab4), _translate("mainWindow", "数据分析"))
